#!/bin/sh

cat mbarrun1/xvg_mbar.log         >  xvg_mbar.log
cat mbarrun2/xvg_mbar.log         >> xvg_mbar.log
cat mbarrun3/xvg_mbar.log         >> xvg_mbar.log
cat mbarrun4/xvg_mbar.log         >> xvg_mbar.log
cat mbarrun5/xvg_mbar.log         >  xvg_mbar.log
cat mbarrun6/xvg_mbar.log         >> xvg_mbar.log
cat mbarrun7/xvg_mbar.log         >> xvg_mbar.log
cat mbarrun8/xvg_mbar.log         >> xvg_mbar.log

cat mbarrun1/xvg_mbartm.log       >  xvg_mbartm.log
cat mbarrun2/xvg_mbartm.log       >> xvg_mbartm.log
cat mbarrun3/xvg_mbartm.log       >> xvg_mbartm.log
cat mbarrun4/xvg_mbartm.log       >> xvg_mbartm.log
cat mbarrun5/xvg_mbartm.log       >  xvg_mbartm.log
cat mbarrun6/xvg_mbartm.log       >> xvg_mbartm.log
cat mbarrun7/xvg_mbartm.log       >> xvg_mbartm.log
cat mbarrun8/xvg_mbartm.log       >> xvg_mbartm.log

./stat.py xvg_mbar*.log

