#!/bin/bash
#$ -V                           # Inherit the submission environment
#$ -cwd                         # Start job in submission directory
#$ -N Tdbl2simul                # Job Name
#$ -j y                         # Combine stderr and stdout
#$ -o $JOB_NAME.o$JOB_ID        # Name of the output file (eg. myMPI.oJobID)
#$ -pe 12way 12                 # Requests 12 tasks/node, 12 cores total
#$ -q normal                    # Queue name normal
#$ -l h_rt=24:00:00             # Run time (hh:mm:ss) - 24.0 hours
#$ -A Proteins-and-DNA-sol      # Account

# make sure to find the correct gromacs
export GMXLIB=$HOME/work/gmx/gromacs5.0/share/top

export mdrun="$HOME/work/gmx/gromacs5.0/buildiccdbl/bin/gmx_d mdrun"

export prj="nvt"

for dir in T420dbl T430dbl T440dbl T450dbl T460dbl T470dbl T480dbl T490dbl T500dbl T510dbl T520dbl T530dbl; do
  cd $dir
  pwd
  if [ -f $prj.cpt ]; then
    OPTCPT="-cpi $prj.cpt"
  else
    OPTCPT=" "
  fi
  # single thread running
  $mdrun -nt 1 -maxh 23.9 -deffnm $prj $OPTCPT &
  cd ..
done

wait

