#!/bin/bash
#$ -V                           # Inherit the submission environment
#$ -cwd                         # Start job in submission directory
#$ -N TP3simul                  # Job Name
#$ -j y                         # Combine stderr and stdout
#$ -o $JOB_NAME.o$JOB_ID        # Name of the output file (eg. myMPI.oJobID)
#$ -pe 12way 12                 # Requests 12 tasks/node, 12 cores total
#$ -q normal                    # Queue name normal
#$ -l h_rt=24:00:00             # Run time (hh:mm:ss) - 24.0 hours
#$ -A Proteins-and-DNA-sol      # Account

# make sure to find the correct gromacs
export GMXLIB=$HOME/work/gmx/gromacs5.0/share/top

export mdrun="$HOME/work/gmx/gromacs5.0/buildicc/bin/gmx mdrun"

export prj="npt"

# be careful about T310P2
for dir in T320P3 T330P4 T340P5 T350P6 T360P7 T370P8 T380P9 T390P10 T400P11 T410P12 T420P13 ; do
  cd $dir
  pwd
  if [ -f $prj.cpt ]; then
    OPTCPT="-cpi $prj.cpt"
  else
    OPTCPT=" "
  fi
  # single thread running
  $mdrun -nt 1 -maxh 23.9 -deffnm $prj $OPTCPT &
  cd ..
done

wait

