#!/bin/bash
#$ -V                           # Inherit the submission environment
#$ -cwd                         # Start job in submission directory
#$ -N Texsimul                  # Job Name
#$ -j y                         # Combine stderr and stdout
#$ -o $JOB_NAME.o$JOB_ID        # Name of the output file (eg. myMPI.oJobID)
#$ -pe 12way 12                 # Requests 12 tasks/node, 12 cores total
#$ -q normal                    # Queue name normal
#$ -l h_rt=24:00:00             # Run time (hh:mm:ss) - 24.0 hours
#$ -A Proteins-and-DNA-sol      # Account

# make sure to find the correct gromacs
export GMXLIB=$HOME/work/gmx/gromacs5.0/share/top

export mdrun="$HOME/work/gmx/gromacs5.0/buildicc/bin/gmx mdrun"

export prj="nvt"

for dir in T450 T500 T550 T600 T650 T700 T750 T800 T850 T900 T950 T1000; do
  cd $dir
  pwd
  if [ -f $prj.cpt ]; then
    OPTCPT="-cpi $prj.cpt"
  else
    OPTCPT=" "
  fi
  # single thread running
  $mdrun -nt 1 -maxh 23.9 -deffnm $prj $OPTCPT &
  cd ..
done

wait

