#!/bin/bash
rsync -avz --exclude="bak*" --exclude="*.py" --exclude="*.sh" \
  --exclude=".*.swp" --exclude="#*" --exclude="*simul.o*" \
  --exclude="ljwham" --exclude="ljwham2" \
  oo1@lonestar.tacc.utexas.edu:/scratch/02464/oo1/wham/data/lj/run* .

